<?php
namespace App;
use Smarty\Smarty;

class SmartyView extends Smarty
{
    public function __construct()
    {
        parent::__construct();
    }

//    public function display( $template = null, $cache_id = null, $compile_id = null )
//    {
//        # if template as format : extends:layout.tpl|index.tpl
//        if ( strpos( $template, 'extends:' ) !== false ) {
//            $template = str_replace( 'extends:', '', $template );
//            $templates = explode( '|', $template );
//            $this->assign( 'content', $templates[1] );
//            $template = $templates[0];
//        }
//        dd( "xs" );
//        parent::display( $template, $cache_id, $compile_id ); // TODO: Change the autogenerated stub
//    }
}